"Circle":
    "position" : [3.35,-0.48,0.0]
    "velocity" : [0.0,0.0,0.0]
    "acceleration" : [0.0,0.0,0.0]
    "rpy" : [0.0,0.0,0.0]
    "angular_velocity" : [0.0,0.0,0.0]
    "angular_acceleration" : [0.0,0.0,0.0]
    "radius" : 0.2
