ModelState:
  stance_type: 1
  next_stance_type: 0
  com_state:
    position: [0, 0, 0.814]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
  left_foot_state:
    position: [0, 0.095, 0]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
    rpy: [0, 0, 0]
    angular_velocity: [0, 0, 0]
    angular_acceleration: [0, 0, 0]
  right_foot_state:
    position: [0, -0.095, 0]
    velocity: [0, 0, 0]
    acceleration: [0, 0, 0]
    rpy: [0, 0, 0]
    angular_velocity: [0, 0, 0]
    angular_acceleration: [0, 0, 0]
