#RobotFootParameters:
#  max_step_len: 0.2
#  min_feet_dist: 0.1569
#  max_feet_dist: 0.25
#  feet_dist_default: 0.1569
#  foot_length: 0.144
#  foot_width: 0.04
#RobotFootParameters:
#  max_step_len: 0.2
#  min_feet_dist: 0.21
#  max_feet_dist: 0.3
#  feet_dist_default: 0.19
#  foot_length: 0.1372
#  foot_width: 0.058
RobotFootParameters:
  max_step_len: 0.5
  min_feet_dist: 0.1569
  max_feet_dist: 0.5
  feet_dist_default: 0.1569
  foot_length: 0.06
  foot_width: 0.06
